// Templates of the slides being generated with the plugin
import preview from "../app/assets/images/slides/BRUTAL/preview.png"

const templateBrutal = {
    metadata: {
        name: "Brutal",
        description: "Brutal design with bold elements",
        availablePalettes: ['BRUTAL1', 'BRUTAL2', 'BRUTAL3'],
        availableFonts: ['Archivo Narrow', 'Outfit', 'Mate'],
        preview: preview,
        tags: [
            { 
                text: "Brutal", 
                backgroundColor: "#F7E3DC",
                textColor: "#802E11"
            },
            { 
                text: "Bold", 
                backgroundColor: "#E3DCF7",
                textColor: "#2E1180"
            }
        ]
    },
    titleSlide: {
    backgroundColorIndex: 0,
    title: "Title Slide",
    instruction: "Use this slide to make a bold first impression with a large title and supporting information. The border elements create a strong frame for your content. Keep the title impactful and the supporting text concise.",
    elements: [
      { type: "rectangle", position: [959, 557], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [943, 540], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 1041], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 1041], size: [34, 1], colorIndex: 1 },
      { type: "text", position: [56, 56], size: [1808, 244], content: "Project title describing it's core value with additional text to add", colorIndex: 1, fontSize: 128, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [56, 894], size: [288, 23], content: "Project", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [360, 894], size: [288, 23], content: "Presented by", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [664, 894], size: [288, 23], content: "Event", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [56, 978], size: [288, 46], content: "Project Name Ambitious project", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "BOTTOM", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [360, 978], size: [288, 46], content: "John Doe Project CEO & Founder", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "BOTTOM", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [664, 978], size: [288, 46], content: "John Doe Project CEO & Founder", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "BOTTOM", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "rectangle", position: [56, 858], size: [8, 8], colorIndex: 1, borderRadius: 9999 },
      { type: "rectangle", position: [360, 858], size: [8, 8], colorIndex: 1, borderRadius: 9999 },
      { type: "rectangle", position: [664, 858], size: [8, 8], colorIndex: 1, borderRadius: 9999 },
      { type: "rectangle", position: [376, 858], size: [8, 8], colorIndex: 1, borderRadius: 9999 },
      { type: "rectangle", position: [680, 858], size: [8, 8], colorIndex: 1, borderRadius: 9999 },
      { type: "rectangle", position: [696, 858], size: [8, 8], colorIndex: 1, borderRadius: 9999 },
    ]
  },
  problemSlide: {
    backgroundColorIndex: 0,
    title: "Problem Slide",
    instruction: "Use this slide to present the problem with a bold headline and supporting statistics. The large percentage number emphasizes the scale of the problem. Keep the problem statement clear and the supporting text focused.",
    elements: [
      { type: "rectangle", position: [959, 557], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [943, 540], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 1041], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 1041], size: [34, 1], colorIndex: 1 },
      { type: "text", position: [56, 56], size: [1808, 244], content: "Short overview of the problem that's being solved with your product", colorIndex: 1, fontSize: 128, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [56, 722], size: [1808, 302], content: "Larger description of the way that product solves the issue. May be longer that a sentence and up to 4 lines of text.", colorIndex: 2, fontSize: 64, alignHorizontal: "LEFT", alignVertical: "BOTTOM", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [56, 630], size: [1808, 243], content: "25%", colorIndex: 1, fontSize: 256, alignHorizontal: "LEFT", alignVertical: "BOTTOM", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [1424, 506], size: [136, 69], content: "Q1 2025 Event Project Name", colorIndex: 1, fontSize: 24, alignHorizontal: "CENTER", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95, opacity: 0.1 },
    ]
  },
  solutionSlide: {
    backgroundColorIndex: 0,
    title: "Solutions Slide",
    instruction: "Use this slide to present your solution with a bold headline and supporting image. The clean layout emphasizes your solution's key features. Make your solution statement compelling and the supporting text clear.",
    elements: [
      { type: "rectangle", position: [959, 557], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [943, 540], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 1041], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 1041], size: [34, 1], colorIndex: 1 },
      { type: "text", position: [56, 56], size: [1808, 244], content: "Short overview of the problem that's being solved with your product", colorIndex: 1, fontSize: 128, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [977, 422], size: [887, 102], content: "Larger description of the way that product solves the issue. May be longer that a sentence and up to 4 lines of text.", colorIndex: 2, fontSize: 32, alignHorizontal: "LEFT", alignVertical: "BOTTOM", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [360, 506], size: [136, 69], content: "Q1 2025 Event Project Name", colorIndex: 1, fontSize: 24, alignHorizontal: "CENTER", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95, opacity: 0.1 },
      { type: "image", imageSrc: "https://raw.githubusercontent.com/ntizish/startup-starter-1/refs/heads/main/src/app/assets/images/slides/BRUTAL/BRUTAL_1.png", position: [977, 558], size: [887, 466]}
    ]
  },
  demoSlide: {
    backgroundColorIndex: 0,
    title: "Demo Slide",
    instruction: "Use this slide to showcase your product's functionality with a split layout. The left side contains feature descriptions, while the right side displays the product interface. Focus on the most important features.",
    elements: [
      { type: "rectangle", position: [959, 557], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [943, 540], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 1041], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 1041], size: [34, 1], colorIndex: 1 },
      { type: "text", position: [56, 56], size: [896, 273], content: "Functionality that's tailored for your need on the go", colorIndex: 1, fontSize: 96, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [56, 422], size: [887, 602], content: "Larger description of the way that product solves the issue. May be longer that a sentence and up to 4 lines of text.", colorIndex: 1, fontSize: 56, alignHorizontal: "LEFT", alignVertical: "BOTTOM", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [360, 506], size: [136, 69], content: "Q1 2025 Event Project Name", colorIndex: 1, fontSize: 24, alignHorizontal: "CENTER", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95, opacity: 0.1 },
      { type: "image", imageSrc: "https://raw.githubusercontent.com/ntizish/startup-starter-1/refs/heads/main/src/app/assets/images/slides/BRUTAL/BRUTAL_2.png", position: [1045.19, 56], size: [754.21, 1558]}
    ]
  },
  demoSlide2: {
    backgroundColorIndex: 0,
    title: "Demo Slide",
    instruction: "Use this slide as an alternative demo presentation with a bold headline and multiple product views. The layout allows for showcasing different aspects or states of your product. Keep the descriptions clear and focused.",
    elements: [
      { type: "rectangle", position: [959, 557], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [943, 540], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 1041], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 1041], size: [34, 1], colorIndex: 1 },
      { type: "text", position: [56, 56], size: [1808, 558], content: "Functionality that's tailored for your need on the go", colorIndex: 1, fontSize: 196, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [575, 506], size: [136, 69], content: "Q1 2025 Event Project Name", colorIndex: 1, fontSize: 24, alignHorizontal: "CENTER", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95, opacity: 0.1 },
      { type: "image", imageSrc: "https://raw.githubusercontent.com/ntizish/startup-starter-1/refs/heads/main/src/app/assets/images/slides/BRUTAL/BRUTAL_2.png", position: [784, 510], size: [437.32, 903.38]},
      { type: "image", imageSrc: "https://raw.githubusercontent.com/ntizish/startup-starter-1/refs/heads/main/src/app/assets/images/slides/BRUTAL/BRUTAL_2.png", position: [1272, 386], size: [437.32, 903.38]}
    ]
  },
  marketSlide: {
    backgroundColorIndex: 0,
    title: "Market Slide",
    instruction: "Use this slide to present market size with a bold number and supporting text. The clean layout emphasizes the market opportunity. Include market size, growth projections, and key market insights.",
    elements: [
      { type: "rectangle", position: [959, 557], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [943, 540], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 1041], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 1041], size: [34, 1], colorIndex: 1 },
      { type: "text", position: [968, 56], size: [896, 0], content: "151.2M", colorIndex: 1, fontSize: 256, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [56, 56], size: [288, 0], content: "$", colorIndex: 1, fontSize: 256, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [56, 722], size: [1808, 302], content: "Larger description of the way that product solves the issue. May be longer that a sentence and up to 4 lines of text.", colorIndex: 2, fontSize: 64, alignHorizontal: "LEFT", alignVertical: "BOTTOM", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [360, 56], size: [288, 0], content: "...", colorIndex: 1, fontSize: 256, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [1424, 506], size: [136, 69], content: "Q1 2025 Event Project Name", colorIndex: 1, fontSize: 24, alignHorizontal: "CENTER", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95, opacity: 0.1 },
    ]
  },
  marketSlide2: {
    backgroundColorIndex: 0,
    title: "Market Slide",
    instruction: "Use this slide as an alternative market presentation with a split layout. Each section can highlight different market aspects or segments. Keep the data clear and the supporting text focused on key insights.",
    elements: [
      { type: "rectangle", position: [959, 557], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [943, 540], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 1041], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 1041], size: [34, 1], colorIndex: 1 },
      { type: "text", position: [968, 558], size: [896, 0], content: "$151.2M", colorIndex: 1, fontSize: 96, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [56, 558], size: [887, 0], content: "$151.2M", colorIndex: 1, fontSize: 96, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [977, 855], size: [887, 169], content: "Larger description of the way that product solves the issue. May be longer that a sentence and up to 4 lines of text.", colorIndex: 2, fontSize: 44, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [56, 855], size: [887, 169], content: "Larger description of the way that product solves the issue. May be longer that a sentence and up to 4 lines of text.", colorIndex: 2, fontSize: 44, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [1576, 56], size: [136, 69], content: "Q1 2025 Event Project Name", colorIndex: 1, fontSize: 24, alignHorizontal: "CENTER", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95, opacity: 0.1 },
    ]
  },
  teamSlide: {
    backgroundColorIndex: 0,
    title: "Team Slide",
    instruction: "Use this slide to introduce your team members in a grid layout. Each team member should have a photo, name, and role description. The consistent spacing creates a professional presentation.",
    elements: [
      { type: "rectangle", position: [959, 557], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [943, 540], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 1041], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 1041], size: [34, 1], colorIndex: 1 },
      { type: "text", position: [360, 971], size: [583, 55], content: "Larger description of the way that product solves the issue.    May be longer that a sentence and up to 2 lines of text.", colorIndex: 2, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [360, 469], size: [583, 55], content: "Larger description of the way that product solves the issue.    May be longer that a sentence and up to 2 lines of text.", colorIndex: 2, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [1281, 469], size: [583, 55], content: "Larger description of the way that product solves the issue.    May be longer that a sentence and up to 2 lines of text.", colorIndex: 2, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [1281, 971], size: [583, 55], content: "Larger description of the way that product solves the issue.    May be longer that a sentence and up to 2 lines of text.", colorIndex: 2, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [56, 469], size: [136, 43], content: "Team player #1", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [56, 971], size: [136, 43], content: "Team player #1", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [977, 469], size: [136, 43], content: "Team player #2", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [977, 971], size: [136, 43], content: "Team player #2", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "image", imageSrc: "https://raw.githubusercontent.com/ntizish/startup-starter-1/refs/heads/main/src/app/assets/images/slides/BRUTAL/BRUTAL_3.png", position: [56, 56], size: [887, 393]},
      { type: "image", imageSrc: "https://raw.githubusercontent.com/ntizish/startup-starter-1/refs/heads/main/src/app/assets/images/slides/BRUTAL/BRUTAL_3.png", position: [977, 56], size: [887, 393]},
      { type: "image", imageSrc: "https://raw.githubusercontent.com/ntizish/startup-starter-1/refs/heads/main/src/app/assets/images/slides/BRUTAL/BRUTAL_3.png", position: [56, 558], size: [887, 393]},
      { type: "image", imageSrc: "https://raw.githubusercontent.com/ntizish/startup-starter-1/refs/heads/main/src/app/assets/images/slides/BRUTAL/BRUTAL_3.png", position: [977, 558], size: [887, 393]}
    ]
  },
  gallerySlide: {
    backgroundColorIndex: 0,
    title: "Gallery Slide",
    instruction: "Use this slide to showcase your product or project through two large images. Each image should have a brief description explaining its significance. The layout creates a strong visual impact.",
    elements: [
      { type: "rectangle", position: [959, 557], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [943, 540], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 1041], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 1041], size: [34, 1], colorIndex: 1 },
      { type: "text", position: [56, 969], size: [583, 55], content: "Brief description.    May be longer that a sentence and up to 2 lines of text.", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [977, 969], size: [583, 55], content: "Brief description.    May be longer that a sentence and up to 2 lines of text.", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "image", imageSrc: "https://raw.githubusercontent.com/ntizish/startup-starter-1/refs/heads/main/src/app/assets/images/slides/BRUTAL/BRUTAL_3.png", position: [56, 56], size: [887, 897]},
      { type: "image", imageSrc: "https://raw.githubusercontent.com/ntizish/startup-starter-1/refs/heads/main/src/app/assets/images/slides/BRUTAL/BRUTAL_3.png", position: [977, 56], size: [887, 897]}
    ]
  },
  contactSlide: {
    backgroundColorIndex: 0,
    title: "Contact Slide",
    instruction: "Use this slide to provide contact information with a bold call-to-action. The border elements frame your content while maintaining readability. Include all relevant contact methods and make the call-to-action clear.",
    elements: [
      { type: "text", position: [56, 56], size: [1808, 436], content: "Shape the world with us!", colorIndex: 1, fontSize: 256, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 85 },
      { type: "text", position: [56, 894], size: [288, 23], content: "Email", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [360, 894], size: [288, 23], content: "Telegram", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [664, 894], size: [288, 23], content: "Website", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [56, 1001], size: [288, 23], content: "wanna@email.me", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "BOTTOM", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [360, 1001], size: [288, 23], content: "@wanna_text_me", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "BOTTOM", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "text", position: [664, 1001], size: [288, 23], content: "wanna-text.me", colorIndex: 1, fontSize: 24, alignHorizontal: "LEFT", alignVertical: "BOTTOM", fontWeight: "Medium", letterSpacing: -1, lineHeight: 95 },
      { type: "rectangle", position: [56, 858], size: [8, 8], colorIndex: 1, borderRadius: 9999 },
      { type: "rectangle", position: [360, 858], size: [8, 8], colorIndex: 1, borderRadius: 9999 },
      { type: "rectangle", position: [664, 858], size: [8, 8], colorIndex: 1, borderRadius: 9999 },
      { type: "rectangle", position: [376, 858], size: [8, 8], colorIndex: 1, borderRadius: 9999 },
      { type: "rectangle", position: [680, 858], size: [8, 8], colorIndex: 1, borderRadius: 9999 },
      { type: "rectangle", position: [696, 858], size: [8, 8], colorIndex: 1, borderRadius: 9999 },
      { type: "text", position: [1728, 955], size: [136, 69], content: "Q1 2025 Event Project Name", colorIndex: 1, fontSize: 24, alignHorizontal: "CENTER", alignVertical: "TOP", fontWeight: "Bold", letterSpacing: -1, lineHeight: 95, opacity: 0.1 },
      { type: "rectangle", position: [959, 557], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [943, 540], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 56], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 39], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [38, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [1880, 1058], size: [34, 1], colorIndex: 1, rotation: 90.0 },
      { type: "rectangle", position: [22, 1041], size: [34, 1], colorIndex: 1 },
      { type: "rectangle", position: [1864, 1041], size: [34, 1], colorIndex: 1 },
    ]
  }
};
  
  export default templateBrutal;